version: "2"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDb
  app:
    build: .
    depends_on: 
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/www/app/src
    command: npm run start:watch